services:
  target:
    build: 
      context: target
      target: ${VERSION:?VERSION is undefined}
  attacker:
    build: attacker-cookies
    environment:
      PROTOCOL: ${PROTOCOL:-http}
      MODE: 'user'
    depends_on:
      - target
  server:
    build: server
    networks:
      default:
        aliases:
          - localtest.me
    ports:
      - 80:80
      - 443:443
    depends_on:
      - target
      - attacker
