version: '3'
services:
  server:
    image: node:18-alpine
    command: node /server.js
    volumes:
      - ./server.js:/server.js
    ports:
      - 80:3000
  proxy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/Caddyfile
    command: caddy run --config /Caddyfile
    ports:
      - 443:443

