services:
  target:
    build: 
      context: target
      target: "${VERSION:?VERSION is undefined}"
  server:
    build: server
    ports:
      - 80:80
      - 443:443
    depends_on:
      - target
