services:
  target:
    build: 
      context: target
      target: "${VERSION:?VERSION is undefined}"
  attacker:
    build: attacker-post-login
    environment:
      PROTOCOL: "${PROTOCOL:?PROTOCOL is undefined}"
    extra_hosts:
    - "localtest.me:${LOCAL_IP:?LOCAL_IP is undefined}"
    depends_on:
      - target
  server:
    build: server
    ports:
      - 80:80
      - 443:443
    depends_on:
      - target
      - attacker
